version: "3.9"

services:
    ims-mysql:
        image: "mysql:8.0.26"
        container_name: "ims-db-mysql"
        volumes:
            - mysql_data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: "${IMS_MYSQL_ROOT_PASSWORD}"
            MYSQL_USER: "${IMS_MYSQL_USER}"
            MYSQL_PASSWORD: "${IMS_MYSQL_USER_PASSWORD}"
            MYSQL_DATABASE: "${IMS_MYSQL_DATABASE}"

volumes:
    mysql_data:
